services:
  - type: web
    name: leadgentax-website
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT router.php
    envVars:
      - key: PHP_VERSION
        value: 8.1
    healthCheckPath: /
    autoDeploy: true

