services:
  - type: web
    name: leadgentax-website
    env: php
    plan: free
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT router.php
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: NODE_VERSION
        value: ~
    healthCheckPath: /
    autoDeploy: true

